
import type { Metadata } from "next";
import { TanstackQueryProvider } from "./tanstack-query-provider";
import StoreProvider from "./StoreProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KisanBazaar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider items={[]}>
        <TanstackQueryProvider>
        {children}
        </TanstackQueryProvider>
        </StoreProvider>
       

        
      
      </body>
    </html>
  );
}
